alloy-rs/op-alloy

Cargo.toml, crates/rpc-types/Cargo.toml
=> chore: rename crates

crates/consensus/src/receipt/envelope.rs, crates/consensus/src/receipt/receipts.rs, crates/rpc-types/src/receipt.rs
closes #18
applies suggested fixes
=> fix: op alloy rpc tx receipt

Cargo.toml
https://github.com/alloy-rs/op-alloy/pull/23
=> chore: downgrad clippy all

crates/consensus/src/transaction/envelope.rs
`OpTxType::Deposit` never generated by arbitrary impl
Choose index from list of possible `OpTxType`s
=> Include deposit in arbitrary testing

Cargo.toml, crates/rpc-types-engine/Cargo.toml, crates/rpc-types-engine/README.md, crates/rpc-types-engine/src/lib.rs, crates/rpc-types-engine/src/payload.rs
Migrate types from  https://github.com/alloy-rs/alloy/blob/main/crates/rpc-types-engine/src/optimism.rs
=> feat: `rpc-types-engine`

Cargo.toml, crates/consensus/src/transaction/deposit.rs, crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/typed.rs, crates/network/Cargo.toml, crates/network/src/lib.rs, crates/rpc-types/src/lib.rs, crates/rpc-types/src/receipt.rs, crates/rpc-types/src/transaction.rs
Patches to latest alloy and also moves optimism-related `OptimismTransactionReceiptFields` and `OptimismTransactionFields` here
=> chore(deps): use latest alloy

crates/rpc-types/src/receipt.rs
Closes https://github.com/alloy-rs/op-alloy/issues/57
Port fields from depreciated alloy type https://github.com/alloy-rs/alloy/commit/ab462f12ac40fd16bd9882c9451d7d62f7c31d37
=> Add ecotone support to `op_alloy_rpc_types::OptimismTransactionReceiptFileds`

.github/ISSUE_TEMPLATE/config.yml
Small PR to remove the ethers-rs telegram contact link.
=> chore: Remove ethers contact link

crates/consensus/src/transaction/deposit.rs
Will be needed in scope of https://github.com/paradigmxyz/reth/issues/9484
=> feat: derive `Arbitrary` for `TxDeposit`

crates/consensus/src/transaction/deposit.rs
Related https://github.com/paradigmxyz/reth/issues/9484 cc @klkvr
=> consensus: make `decode_fields` pub for `TxDeposit`

.github/workflows/ci.yml
Adds a ci check that runs `cargo check` over the feature powerset using [`cargo hack`](https://github.com/taiki-e/cargo-hack).
=> feat: Feature Powerset Job

crates/protocol/src/lib.rs, crates/protocol/src/utils.rs
Adds a simple utility method to tell if a tx is a deposit transaction.
=> feat(protocol): Deposit Tx Utility

Cargo.toml, crates/protocol/Cargo.toml, crates/protocol/src/deposits.rs, crates/protocol/src/lib.rs
related https://github.com/anton-rs/kona/issues/509
=> Feat(op-alloy-protocol): add deposit module 

crates/protocol/src/deposits.rs
ref #81
this removes the generic, doesn't seem reasonable.
and fixes ci
=> chore: cleanup depositerror

crates/rpc-types/src/net.rs
Replaced u8 types with the Connectedness enum 
ref of the implementation https://github.com/libp2p/go-libp2p/blob/d55bed5f78fad923353b92c7d1db64c758bcbf9c/core/network/network.go#L49
related to https://github.com/ethereum-optimism/optimism/blob/40750a58e7a4a6f06370d18dfe6c6eab309012d9/op-node/p2p/rpc_api.go#L25
=> feat(rpc-types): Replace u8 with Connectedness Enum

Cargo.toml, crates/rpc-types/src/receipt.rs
=> chore: bump alloy

crates/consensus/src/hardforks/ecotone.rs, crates/consensus/src/hardforks/fjord.rs, crates/consensus/src/lib.rs, crates/consensus/src/transaction/source.rs
Removes the std feature flag over the extern alloc crate.
=> feat: Remove alloc flag

crates/protocol/src/block_info.rs
Small PR to refactor out block hash retrieval into a `const` function.
=> chore(protocol): Block Hash Refactor

Cargo.toml, crates/consensus/Cargo.toml, crates/consensus/src/lib.rs, crates/consensus/src/receipt/envelope.rs, crates/consensus/src/receipt/receipts.rs, crates/consensus/src/transaction/envelope.rs, crates/genesis/Cargo.toml, crates/genesis/src/lib.rs, crates/genesis/src/rollup.rs, crates/genesis/src/system.rs, crates/network/Cargo.toml, crates/protocol/Cargo.toml, crates/protocol/src/block_info.rs, crates/protocol/src/channel.rs, crates/protocol/src/deposits.rs, crates/protocol/src/frame.rs, crates/protocol/src/lib.rs, crates/provider/Cargo.toml, crates/provider/src/lib.rs, crates/rpc-jsonrpsee/Cargo.toml, crates/rpc-jsonrpsee/src/lib.rs, crates/rpc-types-engine/Cargo.toml, crates/rpc-types-engine/src/lib.rs, crates/rpc-types-engine/src/superchain.rs, crates/rpc-types/Cargo.toml, crates/rpc-types/src/genesis.rs, crates/rpc-types/src/lib.rs, crates/rpc-types/src/net.rs
Cleans up and uses workspace-level lints in crates following Alloy.
=> feat(workspace): Use Workspace Level Lints

crates/protocol/Cargo.toml, crates/protocol/src/channel.rs, crates/rpc-types/Cargo.toml, crates/rpc-types/src/lib.rs, crates/rpc-types/src/net.rs
=> chore: use alloy map

Cargo.toml, crates/consensus/src/receipt/envelope.rs, crates/consensus/src/receipt/receipts.rs, crates/consensus/src/transaction/deposit.rs, crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/typed.rs, crates/network/src/lib.rs, crates/protocol/src/block_info.rs, crates/protocol/src/deposits.rs, crates/rpc-types/Cargo.toml, crates/rpc-types/src/transaction.rs
=> chore: bump alloy 0.4

Cargo.toml, crates/consensus/src/block.rs, crates/consensus/src/lib.rs, crates/protocol/Cargo.toml, crates/protocol/src/block.rs, crates/protocol/src/lib.rs, crates/rpc-types/src/transaction.rs
> [!WARNING]
>
> Stacked ontop of #124 
Introduces an optimism consensus block type.
Closes #93 
Closes #92
=> feat(consensus): OpBlock Type

crates/genesis/README.md
Small PR to update the `op-alloy-genesis` readme.
=> chore(genesis): Small README Update

crates/genesis/src/genesis.rs, crates/genesis/src/rollup.rs, crates/genesis/src/system.rs, crates/protocol/src/utils.rs
Adds the new EIP-1559 parameters to the `SystemConfig` in preparation for the Holocene hardfork.
New config update type is specified [here](https://specs.optimism.io/protocol/holocene/configurability.html#configupdate).
=> feat(genesis): `SystemConfig` holocene updates

CHANGELOG.md, Cargo.toml
=> chore: v0.3.3

Justfile
Adds a `Justfile` with basic targets for my sanity.
=> feat: Justfile for my sanity

Cargo.toml
=> chore: Cleanup Workspace Manifest

crates/genesis/src/rollup.rs, crates/genesis/src/system.rs
Small PR to cleanup arbitrary tests.
=> chore: Cleanup Arbitrary Tests

.github/CODEOWNERS
Update codeowners to include [refcell](https://github.com/refcell) and [clabby](https://github.com/clabby)
=> feat: Codeowner Updates

crates/consensus/src/transaction/deposit.rs, deny.toml
Ref: https://github.com/foundry-rs/foundry/pull/9047 
impl `SignableTransaction<alloy_primitives::Signature>` for `TxDeposit`
=> feat(`consensus`): impl `SignableTx` for `TxDeposit`

crates/rpc-types/src/config.rs
same as https://github.com/alloy-rs/op-alloy/pull/156
=> fix: Genesis l1 l2 field types

crates/consensus/src/transaction/deposit.rs, crates/consensus/src/transaction/envelope.rs, crates/protocol/src/iter.rs
Elides lifetimes to fix nightly lints.
=> fix: Elide Lifetimes

crates/provider/src/ext/engine.rs, crates/rpc-types/src/genesis.rs
=> fix: Op Prefix

Cargo.toml, crates/consensus/src/transaction/deposit.rs, crates/genesis/src/lib.rs, crates/protocol/src/lib.rs, crates/rpc-types-engine/src/envelope.rs, crates/rpc-types-engine/src/lib.rs, crates/rpc-types/Cargo.toml, crates/rpc-types/src/lib.rs
=> chore: Dependency Updates

crates/consensus/src/transaction/typed.rs
=> add arbitrary attr

Cargo.toml, crates/protocol/Cargo.toml, crates/protocol/src/bits.rs, crates/protocol/src/channel.rs, crates/protocol/src/element.rs, crates/protocol/src/errors.rs, crates/protocol/src/lib.rs, crates/protocol/src/signature.rs, crates/protocol/src/span_batch.rs, crates/protocol/src/test_utils.rs, crates/protocol/src/traits.rs, crates/protocol/src/tx_data/eip1559.rs, crates/protocol/src/tx_data/eip2930.rs, crates/protocol/src/tx_data/legacy.rs, crates/protocol/src/tx_data/mod.rs, crates/protocol/src/tx_data/wrapper.rs, crates/protocol/src/txs.rs, crates/protocol/src/utils.rs
Introduces the span batch type.
=> feat(protocol): Span Batch Type

Cargo.toml, crates/protocol/Cargo.toml, crates/protocol/src/bits.rs, crates/protocol/src/channel.rs, crates/protocol/src/element.rs, crates/protocol/src/errors.rs, crates/protocol/src/lib.rs, crates/protocol/src/signature.rs, crates/protocol/src/single_batch.rs, crates/protocol/src/span_batch.rs, crates/protocol/src/test_utils.rs, crates/protocol/src/traits.rs, crates/protocol/src/tx_data/eip1559.rs, crates/protocol/src/tx_data/eip2930.rs, crates/protocol/src/tx_data/legacy.rs, crates/protocol/src/tx_data/mod.rs, crates/protocol/src/tx_data/wrapper.rs, crates/protocol/src/txs.rs, crates/protocol/src/utils.rs, crates/protocol/src/validity.rs
> [!WARNING]
>
> Stacked ontop of #172 
Adds the single batch to op-alloy-protocol.
=> feat(protocol): Single Batch

book/src/building/consensus/README.md, book/src/building/genesis/README.md
Fixes the mdbook missing `READMEs`
=> fix(book): Missing READMEs

book/src/building/consensus/transactions.md, book/src/links.md, book/src/starting/installation.md
=> chore(book): Fix Doc Links

book/src/building/genesis/README.md
=> chore(book): Genesis Docs

book/src/SUMMARY.md, book/src/building/protocol/README.md, book/src/building/protocol/block-info.md, book/src/examples/README.md, book/src/examples/load-a-rollup-config.md
Makes progress on the book section for working with `op-alloy-protocol` types.
=> chore(book): Protocol Docs

crates/protocol/src/batch/transactions.rs, crates/rpc-types/src/lib.rs
Breaks out the small batch decoding fix from #234.
=> fix(protocol): Batch Decoding

Cargo.toml
=> chore: Bump Alloy Deps

crates/consensus/src/transaction/envelope.rs
Bug arbitrary impl
Add missing `OpTxType::Eip7702` to `OpTxType::ALL` list
=> fix(consensus): fix arbitrary impl for `OpTxType`

.github/workflows/book.yml
Previously, the updated mdbook version broke the book.
This pr sets the mdbook version to `0.4.40`.
=> fix(book): Broken Mdbook Version

book/src/building/engine.md, book/src/building/genesis/README.md, book/src/building/protocol/README.md
Small PR to add badges for the crate versions in the book.
=> feat(book): Add Badges for Crates

book/src/building/protocol/batches.md
Adds documentation around `Batch` types.
=> feat(book): Batches

book/src/building/protocol/batches.md, book/src/building/protocol/channels.md, book/src/building/protocol/frames.md
Updates the book with `Channel` docs.
=> feat(book): Channels

book/src/building/protocol/README.md, book/src/building/protocol/batches.md, book/src/building/protocol/channels.md, book/src/building/protocol/frames.md
Adds docs in the op-alloy book for the frame types.
=> feat(book): Frames

book/src/intro.md, book/src/links.md
Touches up the book introduction.
=> chore(book): Touchup Introduction

book/src/starting.md
Micro PR to fix doc links in "Getting Started".
=> fix(book): Getting Start Links

crates/consensus/src/transaction/envelope.rs
adds encodeable+decodable+partialeq
=> feat: add missing OpTxType trait impls

book/src/building/README.md
Provides a preamble on types available in building docs.
=> chore(book): Building Docs

crates/protocol/src/batch/transactions.rs
Protected bits are only present for legacy transactions and we should respect transaction type when getting them in `full_txs`
=> fix: protected bits handling

CHANGELOG.md, Cargo.toml
Releases `v0.6.6` of `op-alloy`.
=> release: v0.6.6

crates/protocol/src/test_utils.rs
Small PR to remove unused method.
=> chore(protocol): Rm Unused Method

CHANGELOG.md, Cargo.toml
Adds `0.6.8` release artifacts.
=> release: 0.6.8

.github/ISSUE_TEMPLATE/BUG-FORM.yml, .github/ISSUE_TEMPLATE/FEATURE-FORM.yml
Small PR updating the issue templates with proper crates.
=> chore: Issue Template Update

book/src/SUMMARY.md, book/src/examples/README.md, book/src/examples/new-l1-block-info-tx-hardfork.md
Adds an example to the `op-alloy` book that walks through implementing `L1BlockInfo` hardfork changes in `op-alloy`.
Closes #279
=> feat(book): Hardfork Change Example

crates/consensus/README.md, crates/genesis/README.md, crates/network/README.md, crates/op-alloy/README.md, crates/protocol/README.md, crates/provider/README.md, crates/registry/README.md, crates/rpc-jsonrpsee/README.md, crates/rpc-types-engine/README.md, crates/rpc-types/README.md
Touches up crate documentation with badges.
=> chore(workspace): Touchup crate docs with badges

crates/rpc-types-engine/Cargo.toml, crates/rpc-types-engine/src/lib.rs, crates/rpc-types-engine/src/versions.rs
Introduces an FCU version for downstream engine api use.
=> feat(engine): FCU Version

crates/consensus/Cargo.toml, crates/genesis/Cargo.toml, crates/protocol/Cargo.toml, crates/rpc-types-engine/Cargo.toml
Based on https://github.com/alloy-rs/op-alloy/pull/329
Incomplete arbitrary feature propagation
Enables `alloy-primitives/arbitrary` in local `arbtirary` feature
=> Propagate arbitrary

crates/rpc-jsonrpsee/src/traits.rs
ref 
https://github.com/paradigmxyz/reth/issues/13092
and
https://github.com/ethereum-optimism/op-geth/blob/0a46245ccc5c801e7b18c258aceb5327d8ad69ad/eth/api_miner.go#L60-L62
=> feat: add miner extension trait

crates/genesis/src/chain.rs, crates/genesis/src/rollup.rs, crates/registry/src/test_utils/base_mainnet.rs, crates/registry/src/test_utils/base_sepolia.rs, crates/registry/src/test_utils/op_mainnet.rs, crates/registry/src/test_utils/op_sepolia.rs, crates/rpc-types/src/genesis.rs
Closes https://github.com/alloy-rs/op-alloy/issues/328
Adds placeholder field for `isthmus_time` in `op-alloy-genesis`.
=> Add placeholder for isthmus time to genesis

CHANGELOG.md, Cargo.toml
Releases `0.7.3` crates for `op-alloy`.
=> release: 0.7.3

Cargo.toml
=> chore: Bump alloy to 0.7.3

crates/consensus/src/transaction/tx_type.rs
=> feat: add serde for OpTxType

crates/consensus/src/transaction/deposit.rs, crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/typed.rs, crates/rpc-types/src/transaction.rs
=> chore: reorder impl fns

crates/consensus/src/transaction/typed.rs
This would be nice to have since it's a variant
`impl From<TxEip7702> for OpTypedTransaction`
=> feat: impl From<TxEip7702> for OpTypedTransaction

.github/workflows/ci.yml
Closes https://github.com/alloy-rs/op-alloy/issues/353
Update target `wasm32-wasi` to `wasm32-wasip1` for ci
=> chore(ci): Update target `wasm32-wasi` to `wasm32-wasip1` for ci

CHANGELOG.md
=> release 0.9.3 p2

CHANGELOG.md, Cargo.toml
=> release: 0.9.3

CHANGELOG.md, Cargo.toml
=> release: 0.9.4

CHANGELOG.md, Cargo.toml
=> release: 0.9.5

Cargo.toml, crates/consensus/src/receipt/envelope.rs, crates/consensus/src/transaction/pooled.rs, crates/provider/src/ext/engine.rs, crates/rpc-types/src/receipt.rs
Bump alloy to the next version.
=> chore: bump alloy 0.11

CHANGELOG.md, Cargo.toml
Release artifacts for `0.10.1`
=> release: 0.10.1

CHANGELOG.md, Cargo.toml
Patch release to fix network upgrade txs
=> release: 0.10.2

crates/rpc-types-engine/src/lib.rs, crates/rpc-types-engine/src/payload_v4.rs
add opstack specific V4 payload type
=> feat: add OpExecutionPayloadV4

crates/rpc-types-engine/src/attributes.rs, crates/rpc-types-engine/src/envelope.rs, crates/rpc-types-engine/src/lib.rs, crates/rpc-types-engine/src/payload/v3.rs, crates/rpc-types-engine/src/payload/v4.rs, crates/rpc-types/src/lib.rs, crates/rpc-types/src/receipt.rs
=> fix: std leakage

crates/rpc-types-engine/src/lib.rs, crates/rpc-types-engine/src/sidecar.rs
Ref #430 
Removed `IsthmusPayloadFields` and its related fuctions
=> feat: remove IsthmusPayloadFields

crates/consensus/src/receipt/receipts.rs, crates/consensus/src/transaction/tx_type.rs
=> chore: make test compile

crates/consensus/src/alloy_compat.rs, crates/consensus/src/transaction/envelope.rs
adds some additional conversion helpers
=> feat: add tryfrom envelope conversions

crates/rpc-types-engine/Cargo.toml, crates/rpc-types-engine/src/envelope.rs, crates/rpc-types-engine/src/payload/mod.rs
Ref #421 
Implemented some functions for `OpExecutionData` similar to `ExecutionData` from alloy
=> feat: impl OpExecutionData

crates/rpc-types-engine/src/lib.rs, crates/rpc-types-engine/src/payload/error.rs, crates/rpc-types-engine/src/payload/mod.rs, crates/rpc-types-engine/src/sidecar.rs
Closes https://github.com/alloy-rs/op-alloy/issues/439
- Adds `OpPayloadError` as extension of `PayloadError` with op variants
=> feat(l2-withdrawals): impl conversion payload + sidecar into block 

crates/consensus/src/transaction/envelope.rs
ref https://github.com/alloy-rs/alloy/pull/2070
=> feat: add signed conversion

crates/rpc-types-engine/src/envelope.rs, crates/rpc-types-engine/src/payload/v4.rs
Ref #450 
Added:
- `parent_beacon_block_root`
- `withdrawals`
=> feat: added helpers for opExecutionData

crates/rpc-types-engine/src/envelope.rs, crates/rpc-types-engine/src/payload/mod.rs
=> chore: fix imports

crates/consensus/src/alloy_compat.rs
Ref #449 
Implement TryFrom<AnyRpcTransaction> for OpTxEnvelope
=> feat: impl AnyRpcTransaction for OpTxEnvelope

crates/rpc-types-engine/src/envelope.rs, crates/rpc-types-engine/src/payload/mod.rs, crates/rpc-types-engine/src/payload/v4.rs
Adds conversion from block to `OpExecutionPayload` and `OpExecutionData`
=> Add conversions from block to payload

crates/rpc-types-engine/src/payload/mod.rs
Bugfix
Bug: empty root hash used instead of empty requests hash
=> fix(engine): Empty requests hash

CHANGELOG.md, Cargo.toml
Release artifacts for `0.10.9`
=> release: 0.10.9

Cargo.toml, crates/consensus/src/transaction/typed.rs
same as https://github.com/alloy-rs/alloy/pull/2172
=> chore: remove associated constant from RlpEcdsaEncodableTx

crates/rpc-types-engine/src/envelope.rs, crates/rpc-types-engine/src/payload/mod.rs, crates/rpc-types-engine/src/payload/v4.rs
Adds support for the V4 CL network payload, introduced with Isthmus.
=> feat(rpc-types-engine): Support V4 network payload

Cargo.toml, crates/consensus/src/receipt/receipts.rs, crates/consensus/src/transaction/deposit.rs, crates/rpc-types-engine/Cargo.toml, crates/rpc-types-engine/src/sidecar.rs
=> chore: Update Dependencies

crates/rpc-types-engine/Cargo.toml, crates/rpc-types-engine/src/lib.rs, crates/rpc-types-engine/src/superchain.rs
Part of https://github.com/paradigmxyz/reth/issues/15243.
Export https://github.com/op-rs/kona/blob/main/crates/node/rpc/src/superchain.rs#L24 in `op-alloy-rpc-types-engine` crate.
=> feat(op-alloy-rpc-types-engine): add `superchain` mod

crates/consensus/src/interop.rs, crates/consensus/src/lib.rs
ref https://github.com/paradigmxyz/reth/pull/15105
fyi @SozinM
=> feat: move safety level

crates/consensus/src/transaction/envelope.rs
ref https://github.com/paradigmxyz/reth/pull/15629
=> chore: rm borrow attr

Cargo.toml, crates/consensus/Cargo.toml, crates/consensus/src/receipt/receipts.rs, crates/consensus/src/transaction/deposit.rs, crates/consensus/src/transaction/envelope.rs
Ref https://github.com/alloy-rs/alloy/issues/2295
Update bincode to 2.0
- Bumps bincode
- Addresses breaking changes in tests
=> chore(deps): bincode 2.0

crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/pooled.rs
missing conversions towards https://github.com/paradigmxyz/reth/issues/15627
=> feat: add missing conversions

Cargo.toml, crates/consensus/src/transaction/deposit.rs, crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/pooled.rs, crates/consensus/src/transaction/typed.rs, crates/rpc-types-engine/src/envelope.rs, crates/rpc-types/src/transaction/request.rs
=> chore: alloy 1.0

crates/consensus/src/transaction/envelope.rs
=> feat: added OpTxEnvelope::try_into_recovered

crates/consensus/src/transaction/envelope.rs, crates/rpc-types-engine/Cargo.toml, crates/rpc-types-engine/src/attributes.rs
=> feat: added recover helpers for OpPayloadAttributes

crates/consensus/src/transaction/envelope.rs
=> chore: add new_unchecked

CHANGELOG.md, Cargo.toml
Publishes the `v0.15.1` release artifacts.
=> chore: release 0.15.1

Cargo.toml, crates/consensus/src/receipt/envelope.rs, crates/consensus/src/transaction/deposit.rs, crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/pooled.rs, crates/consensus/src/transaction/tx_type.rs, crates/consensus/src/transaction/typed.rs
towards https://github.com/paradigmxyz/reth/issues/16026
cc @18aaddy
=> chore: add istyped support

CHANGELOG.md, Cargo.toml
Contains release artifacts for `0.15.7`.
=> release: 0.15.7

Cargo.toml, crates/consensus/src/transaction/envelope.rs, crates/rpc-types-engine/src/attributes.rs
=> chore: bump alloy 1.0.0

README.md
=> docs: added a new badge to the license

crates/network/Cargo.toml, crates/network/src/lib.rs
ref https://github.com/alloy-rs/alloy/pull/2479
ref https://github.com/alloy-rs/alloy/issues/2478
Impl `RecommendedFillers` so that a provider with the correct fillers can be built for the Optimism network.
=> feat(`network`): impl RecommendedFillers for Optimism

crates/consensus/src/transaction/meta.rs, crates/consensus/src/transaction/mod.rs
these will allow us to offload this impl entirely
https://github.com/paradigmxyz/reth/blob/4df1425fcf860572331c682cf868d0a94129536f/crates/optimism/rpc/src/eth/transaction.rs#L93-L97
ref https://github.com/paradigmxyz/reth/issues/16451
=> feat: add meta helpers

CHANGELOG.md, Cargo.toml
=> release: 0.18.1

crates/rpc-types/src/transaction.rs
=> fix: move `Transaction::from_transaction`

crates/consensus/src/transaction/pooled.rs
=> feat: derive `TransactionEnvelope` for `OpPooledTransaction`

book/src/links.md
https://docs.rs/op-alloy-consensus/latest/op_alloy_consensus/enum.OpTxType.html - dead link
https://docs.rs/op-alloy-consensus/latest/op_alloy_consensus/transaction/enum.OpTxType.html - new link
=> fix links.md

crates/consensus/src/receipt/receipts.rs
=> chore: add receipt helpers

crates/consensus/src/receipt/envelope.rs, crates/consensus/src/receipt/receipts.rs
missing helpers for mapping logs, mirrors alloy
cc @cakevm
=> feat: add map logs helpers

crates/rpc-types/src/genesis.rs
Add jovian time for https://github.com/paradigmxyz/reth/issues/17665.
Add `jovian_time` to `OpGenesisInfo`.
=> feat: add `jovian_time` to `OpGenesisInfo`

crates/rpc-types-engine/src/superchain.rs
fixed 2 small typos in code comments
=> chore: fix grammatical typos

crates/rpc-types/src/receipt.rs
=> chore: fix typo in comment

crates/consensus/src/transaction/typed.rs
same as https://github.com/alloy-rs/alloy/pull/2832
=> chore: add into_envelope helper

crates/consensus/src/transaction/envelope.rs
=> feat: add missing signature helper fn
