crates/rpc-types/Cargo.toml, crates/rpc-types/src/genesis.rs
Adds functionalities to extract Optimism genesis data from genesis.
`extract_from` returns `Option` since the extraction can be unsuccessful - negative case should be handled outside.
=> feat: extract optimism genesis info

Cargo.toml, crates/consensus/Cargo.toml, crates/consensus/src/transaction/envelope.rs, crates/network/src/lib.rs
Closes https://github.com/alloy-rs/op-alloy/issues/22
Replaces `alloy_consensus::TxType` with `op_alloy_consensus::TxType` for `<Optimism as Network>::TxType`.
Some methods, are yet to be implemented for deposit tx, and hence will only work for l1 tx types atm, but is out of scope of this pr:
=> Include deposit tx type in `alloy_network::Network` impl

crates/rpc-types/src/genesis.rs
Support the upcoming Optimism Granite hardfork.
Adds a `granite_time` config value to the `OptimismGenesisInfo` struct
=> Add granite_time to OptimismGenesisInfo

crates/network/src/lib.rs, crates/rpc-types/src/transaction.rs
`alloy_network::Network` impl for `Optimism` needs to have unique types as associated types for integration in reth rpc
Replace `alloy_rpc_types_eth::Transaction` with `op_alloy_rpc_types::Transaction` for `Optimism::TransactionResponse`
=> Set `op_alloy_rpc_types::Transaction` as `Optimism::TransactionResponse`

crates/rpc-types/src/lib.rs, crates/rpc-types/src/net.rs
**Description**
Moves Optimism p2p "net" types from `reth/optimism/rpc` into op-alloy for use in other https://github.com/paradigmxyz/op-rs services.
Closes #38
=> feat(rpc-types): p2p Net Types

crates/rpc-types/src/lib.rs, crates/rpc-types/src/sync.rs
Motivation
Issue [reth Issue by matsee ](https://github.com/paradigmxyz/reth/issues/10509)
[Pr comments](https://github.com/paradigmxyz/op-rs/pull/25)
In the pr matsee suggested we should add types here and import there for usage 
Solution
So as mentioned in issue and pr I moved the types here.
Basically added three types here L1/L2blockref and syncstatus
=> feat: Added sync file with types from reth

crates/rpc-jsonrpsee/src/traits.rs, crates/rpc-types/src/lib.rs, crates/rpc-types/src/safe_head.rs
The `RollupNode` trait was missing the `optimism_safeHeadAtL1Block` endpoint.
See reference: https://github.com/ethereum-optimism/optimism/blob/137207200ea23ae0f7d438b8cd96815e79ffb1ed/op-node/node/api.go#L144-L157
=> fix(rpc): Add Missing Safe Head Endpoint

Cargo.toml, crates/protocol/Cargo.toml, crates/protocol/README.md, crates/protocol/src/block.rs, crates/protocol/src/channel.rs, crates/protocol/src/frame.rs, crates/protocol/src/lib.rs
Introduce core protocol types to a new `op-alloy` crate called `op-alloy-protocol`.
Nomenclature: `protocol` as opposed to `derive` since these types will be used beyond derivation. They exist as core types used for data transformation between source and destination chains.
This migrates [channel types](https://github.com/ethereum-optimism/kona/blob/main/crates/primitives/src/channel.rs) and [frame types](https://github.com/ethereum-optimism/kona/blob/main/crates/primitives/src/frame.rs) to op-alloy.
> [!NOTE]
>
> This PR will not include batch types.
> Before these can be ported from the `kona-derive::batch` module, batch validity must be trait abstracted in order to avoid pulling in `kona-derive` types.
=> feat(protocol): Core Protocol Types

crates/rpc-types/src/receipt.rs
Closes https://github.com/alloy-rs/op-alloy/issues/54
- Moves L1 block info fields out of type `OptimismTransactionReceiptFields` into new type `L1BlockInfo`.
- Adds `L1BlockInfo` to `OpTransactionReceipt`
=> fix(rpc): Add l1 block info to OpTransactionReceipt

Cargo.toml, crates/consensus/Cargo.toml
`derive_more` dependency with `full` default features includes `std`, breaking `no_std` compatibility. This PR fixes `no_std` compat by toggling `default-features = false`.
=> fix(consensus): no_std Compatibility

.github/workflows/no_std.yml
Adds a workflow to validate no_std compatibility for a matrix of crates, including only `op-alloy-consensus` for now.
=> feat: Workflow to validate no_std Compatibility

crates/rpc-types/src/receipt.rs
Docs bug: l1 gas used is deprecated since Fjord not Ecotone
https://github.com/ethereum-optimism/op-geth/blob/f2e69450c6eec9c35d56af91389a1c47737206ca/core/types/receipt.go#L90
Update docs
=> fix(docs): l1 gas used deprecated since Fjord not Ecotone

crates/protocol/Cargo.toml, crates/protocol/src/block.rs, crates/protocol/src/channel.rs
Uses the native `u64` type - this prevents a lot of type conversions in kona.
See https://github.com/anton-rs/kona/pull/495
=> fix(protocol): Native u64

crates/protocol/src/lib.rs, crates/protocol/src/utils.rs
Fixes the deposit util to be for EIP 2718.
Renames:
`starts_with_2781_deposit` to
`starts_with_2718_deposit`
=> fix(protocol): EIP 2718 Deposit Tx Utility

Cargo.toml, crates/protocol/src/block.rs, crates/protocol/src/block_info.rs
Re-uses [`alloy_eips::BlockNumHash`](https://docs.rs/alloy-eips/latest/alloy_eips/eip1898/type.BlockNumHash.html) instead of a custom `BlockID` type in `superchain-primitives`.
This follows #91
=> fix: Remove Block ID

Cargo.toml, crates/rpc-types-engine/Cargo.toml, crates/rpc-types-engine/src/payload.rs
> [!WARNING]
>
> Depends on optional serde support in `alloy-rpc-types-engine` https://github.com/alloy-rs/alloy/pull/1283.
Adds an attributes with parent object that's [needed by `kona`](https://github.com/anton-rs/kona/issues/510).
=> feat(engine): Attributes and Optional Serde

crates/rpc-types/src/sync.rs
Currently, `l1_origin` in the `L2BlockRef` struct is an enum. But from the link embedded above it, it is supposed to be a struct. 
See: https://github.com/ethereum-optimism/optimism/blob/develop/op-service/eth/id.go#L10-L13
=> Make `l1_origin` in `L2BlockRef` a struct instead of an enum

Cargo.toml, crates/genesis/Cargo.toml, crates/genesis/README.md, crates/genesis/src/addresses.rs, crates/genesis/src/chain.rs, crates/genesis/src/genesis.rs, crates/genesis/src/lib.rs, crates/genesis/src/params.rs, crates/genesis/src/rollup.rs, crates/genesis/src/system.rs, scripts/check_no_std.sh
Introduces an `op-alloy-genesis` crate similar to [`alloy-genesis`](https://docs.rs/alloy-genesis/latest/alloy_genesis/) that contains Optimism genesis types.
This is part of an effort to remove _both_ `superchain-primitives` and `kona-primitives` to place all optimism core types in `op-alloy` crates.
=> feat: Genesis Types

crates/genesis/src/lib.rs
Re-exports items in `op-alloy-genesis` modules.
=> chore(genesis): Re-exports Inner Items

Cargo.toml, crates/network/Cargo.toml, crates/rpc-types/Cargo.toml, crates/rpc-types/src/lib.rs, crates/rpc-types/src/net.rs, crates/rpc-types/src/receipt.rs, crates/rpc-types/src/transaction.rs
`no_std` support for the `op-alloy-rpc-types` crate. Also does some nice cleanup. Need to add doc comments to the `net` module.
=> feat(rpc-types): no_std Support

crates/rpc-types-engine/Cargo.toml, crates/rpc-types-engine/src/lib.rs, crates/rpc-types-engine/src/payload.rs
Adds `no_std` support to `op-alloy-rpc-types-engine` now that upstream `alloy-rpc-types-engine` has `no_std` support.
=> feat(rpc-types-engine): no_std Support

Cargo.toml, crates/protocol/Cargo.toml, crates/protocol/src/block_info.rs
Removes the [`superchain-primitives`](https://crates.io/crates/superchain-primitives) crate as a dependency.
It is now deprecated in favor of `op-alloy-genesis`.
Bindings for the go [`superchain-registry`](https://github.com/ethereum-optimism/superchain-registry) now live in the [`superhcain`](https://crates.io/crates/superchain) crate.
=> feat: Superchain Primitives Removal

crates/protocol/src/frame.rs
Fixes unchecked frame indexing using the data length.
Also adds some more tests surrounding the `Frame` type to unit test this behaviour.
Closes #107.
=> fix(protocol): Invalid Frame Data Length

crates/rpc-types-engine/src/lib.rs, scripts/check_no_std.sh
`op-alloy-rpc-types-engine` was missing the `no_std` attribute. This adds it in with added `no_std` checks in ci.
=> fix: no_std for op-alloy-rpc-types-engine

crates/rpc-types-engine/src/payload_v4.rs
Adds a small serde roundtrip test for the v4 execution payload, adding on empty deposit, withdrawal, and consolidation request lists to the v3 example payload.
=> chore(engine): Execution Payload V4 Serde Test

crates/rpc-types-engine/src/lib.rs
Deprecates the need to pass a reference to the full `RollupConfig` object, using the more lightweight `ChainGenesis` object.
=> feat(engine): Deprecate RollupConfig Argument

crates/rpc-types-engine/src/errors.rs
Fixes `op-alloy-rpc-types-engine` conversion errors to provide their source for 2718 decoding errors and block info decoding errors.
=> fix(engine): Missing Error Source

crates/rpc-types/src/sync.rs
Currently, I'm not able to deserialize the response from `optimism_outputAtBlock` with the `OutputResponse` type. It is happening because the `serde(rename = ..)` is set to `l1Origin` instead of `l1origin`.
According to the [link](https://github.com/ethereum-optimism/optimism/blob/develop/op-service/eth/id.go#L33) embedded in the code, it should be `l1origin`.
=> l1Origin -> l1origin during deser of `L2BlockRef`

.github/workflows/ci.yml, Cargo.toml, crates/provider/Cargo.toml, crates/provider/README.md, crates/provider/src/ext/engine.rs, crates/provider/src/ext/mod.rs, crates/provider/src/lib.rs, crates/rpc-types-engine/Cargo.toml, crates/rpc-types-engine/src/lib.rs, crates/rpc-types-engine/src/superchain.rs
Adds a `provider` crate (`op-alloy-provider`) with some extension API traits for the OP engine API.
Additionally, adds the `SuperchainSignal` type along with the canonical decoding impl for the V0 type.
Ref: https://github.com/paradigmxyz/op-rs/issues/11
=> feat(provider): OP engine api trait ext + superchain signal type

crates/protocol/src/batch_tx.rs, crates/protocol/src/block_info.rs, crates/protocol/src/channel.rs, crates/protocol/src/deposits.rs, crates/protocol/src/frame.rs, crates/protocol/src/lib.rs
Cleans up the `op-alloy-protocol` crate, removing `#[cfg(feature = "std")]` feature gates across the crate.
Also touches up some imports.
=> fix(protocol): Clean up std feature gating

crates/protocol/src/block_info.rs, crates/protocol/src/lib.rs, crates/rpc-types-engine/src/lib.rs
Updates the [`L1BlockInfoTx`](https://github.com/alloy-rs/op-alloy/blob/main/crates/protocol/src/block_info.rs#L41) in `op-alloy-protocol` to include EIP 1559 denominator and elasticity parameters. This extends the `L1BlockInfoTx` with a new `Holocene` variant.
See the [Holocene L1 block attributes specs](https://specs.optimism.io/protocol/holocene/l1-attributes.html#l1-block-attributes) for the transaction byte representation.
See https://github.com/anton-rs/kona/issues/564
=> feat(protocol): Holocene Support

crates/genesis/src/system.rs
Simplifies the log update methods of the `SystemConfig` to accept bool flags if ecotone is active instead of requiring the full `RollupConfig` object. Intentionally simplifies arguments.
Closes #99
=> feat(genesis): Simplify Log Updates in System Config

crates/consensus/Cargo.toml, crates/consensus/src/lib.rs, crates/consensus/src/transaction/deposit.rs, crates/consensus/src/transaction/mod.rs
https://github.com/alloy-rs/alloy/issues/1349
Same as https://github.com/alloy-rs/alloy/pull/1397
=> feat(consensus): bincode compatibility

crates/protocol/src/block_info.rs, crates/protocol/src/lib.rs, crates/protocol/src/utils.rs
Removes the `Holocene` variant of the L1 info transaction. The specification of the dynamic EIP-1559 parameters has changed to put this feature in the `PayloadAttributes` instead.
https://github.com/ethereum-optimism/specs/pull/404
=> chore(protocol): Remove `L1BlockInfoTx::Holocene` variant

crates/rpc-types-engine/src/attributes.rs
Adds the `eip1559Params` field to the `OptimismPayloadAttributes, per https://github.com/ethereum-optimism/specs/pull/404
=> feat(rpc-types-engine): EIP-1559 parameters in `OptimismPayloadAttributes`

crates/protocol/src/frame.rs, crates/protocol/src/iter.rs, crates/protocol/src/lib.rs
Post-holocene, `kona-derive` performs [prunes](https://github.com/anton-rs/kona/blob/main/crates/derive/src/stages/frame_queue.rs#L62-L109) `Frame`s using **forwards**-invalidation. Once the `FrameQueue` stage in the pipeline pulls in encoded frame data from the previous stage, it decodes the data into individual frames and then once all decoded, it prunes invalid frames.
Instead of parsing all frames, we can construct an iterator over encoded `Frame` data, both encoding and pruning each frame individually as they are parsed from the raw, encoded data.
=> feat(protocol): Add Frame Iterator

crates/genesis/src/rollup.rs
Updates the arbitrary `BaseFeeParams` to bound to types. 
See [discussion here](https://github.com/alloy-rs/op-alloy/pull/144#discussion_r1787856319)
=> fix(genesis): BaseFeeParams Arbitrary Bounds

crates/consensus/src/receipt/envelope.rs, crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/typed.rs
EIP-4844 transactions are not supported on OP stack networks https://specs.optimism.io/protocol/exec-engine.html#ecotone-disable-blob-transactions
Removes 4844 variants from transaction and receipt consensus types.
We still have those on RPC types, should we introduce op-specific RPC types? it would also unblock https://github.com/alloy-rs/op-alloy/pull/121
=> fix: remove 4844 transaction type

crates/consensus/src/transaction/envelope.rs
Small PR to add an `is_system_transaction` method to the `OpTxEnvelope` that applies to deposit transactions.
Upstreams [this bit of logic in kona](https://github.com/anton-rs/kona/blob/main/crates/executor/src/util.rs#L73-L79).
=> feat(consensus): System Transaction

crates/rpc-types/src/safe_head.rs
closes https://github.com/alloy-rs/op-alloy/issues/155
reminder op `eth.BlockId` is `alloy::BlockNumHash`
worth checking if we have this wrong anywhere else
=> fix: safeheadresponse field types

crates/provider/src/ext/engine.rs, crates/rpc-types-engine/src/attributes.rs, crates/rpc-types-engine/src/lib.rs, crates/rpc-types-engine/src/payload_v3.rs, crates/rpc-types-engine/src/payload_v4.rs
Modifies OP Stack types in `rpc-types-engine` to use the `Op` prefix as opposed to `Optimism` prefix.
Makes progress on #150
=> fix(rpc-types-engine): Op Prefix Naming Convention

crates/consensus/src/transaction/envelope.rs
We use this pattern downstream (cc @kien-rise):  
https://github.com/risechain/pevm/blob/bed6f220c343d03e6bef0dc7540c531444450d57/src/chain/optimism.rs#L85-L88 
Which doesn't work for `TxEip7702`.
Add the missing `From<Signed<TxEip7702>>` for completeness.
=> feat(envelope): add missing `From<Signed<TxEip7702>>`

crates/genesis/src/rollup.rs
Adjusts the `RollupConfig` type to backwards-activate forks. Right now, if partially constructed with only a later fork timestamp set, prior forks aren't activated. This causes inconsistency in testing in `kona` in a way that's easy to miss.
=> feat(rollup): Backward-activate forks in `RollupConfig`

.github/workflows/ci.yml, crates/consensus/src/transaction/deposit.rs
`optimism_deposit_tx_signature` function in `reth`  should be moved to `op-alloy` as part of an [issue](https://github.com/paradigmxyz/reth/issues/11781).
https://github.com/paradigmxyz/reth/issues/11781
An associated function `signature` is added to the `TxDeposit` struct.
=> feat: add signature function to TxDeposit

Cargo.toml, crates/consensus/src/receipt/envelope.rs, crates/consensus/src/receipt/receipts.rs, crates/consensus/src/traits.rs, crates/consensus/src/transaction/deposit.rs, crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/typed.rs, crates/provider/src/ext/engine.rs, crates/rpc-types-engine/src/payload_v4.rs, crates/rpc-types/src/transaction.rs
There is no longer a V4 execution payload in Pectra, so it does not make sense that there would be one for Optimism. The v4 payload envelope still exists, but it now wraps a v3 payload.
See also https://github.com/alloy-rs/alloy/pull/1383
Based on https://github.com/alloy-rs/op-alloy/pull/175
Remove the V4 payload.
=> chore: bump alloy and remove `OpExecutionPayloadV4`

crates/rpc-types/src/receipt.rs, crates/rpc-types/src/transaction.rs
Adds `{Try}From` implementations for the RPC receipt / transaction type into the `op-alloy-consensus` `OpReceiptEnvelope` + `OpTxEnvelope` counterparts.
closes #181
=> feat(rpc-types): `{Try}From` impl for `OpTransactionReceipt` + `Transaction` -> consensus types

CHANGELOG.md, Cargo.toml
Releases `0.5.1`.
Unblocks @clabby from refactoring `kona-host` to remove the `debug_*` endpoints since https://github.com/alloy-rs/op-alloy/pull/183 was merged.
=> chore: release 0.5.1

crates/protocol/src/batch/errors.rs, crates/protocol/src/batch/mod.rs, crates/protocol/src/lib.rs
Ports batch error types to `op-alloy-protocol`.
=> feat(protocol): Batch Error Types

crates/protocol/Cargo.toml, crates/protocol/src/batch/element.rs, crates/protocol/src/batch/mod.rs, crates/protocol/src/lib.rs, crates/protocol/src/utils.rs
Ports the span batch element type to `op-alloy-protocol`.
=> feat(protocol): Span Batch Element

Cargo.toml, crates/protocol/Cargo.toml, crates/protocol/src/batch/mod.rs, crates/protocol/src/batch/transactions.rs, crates/protocol/src/lib.rs
Ports the batch transactions to `op-alloy-protocol`.
=> feat(protocol): Span Batch Transactions

crates/protocol/src/batch/mod.rs, crates/protocol/src/batch/span.rs, crates/protocol/src/lib.rs
Ports the Span Batch Type to `op-alloy-protocol`. A follow-on pr will implement batch validation and the prefix check.
=> feat(protocol): Span Batch Type

Cargo.toml, crates/protocol/Cargo.toml, crates/protocol/src/batch/span.rs, crates/protocol/src/lib.rs, crates/protocol/src/test_utils.rs
Ports span batch validity checks to `op-alloy-protocol`.
=> feat(protocol): Span Batch Validity Checks

CHANGELOG.md, Cargo.toml
Release `op-alloy-*` `v0.5.2` including ported batch types, improved crate hygiene, and more.
=> chore: Release 0.5.2

README.md, book/src/CONTRIBUTING.md, book/src/LICENSE.md, book/src/building/rollup-configs.md, book/src/intro.md, book/src/starting/installation.md
Sets up the initial structure for the `op-alloy` book.
=> feat: Book Setup

crates/network/Cargo.toml, crates/network/src/lib.rs, crates/rpc-types/Cargo.toml, crates/rpc-types/src/lib.rs, crates/rpc-types/src/transaction.rs, crates/rpc-types/src/transaction/request.rs, scripts/check_no_std.sh
Closes https://github.com/alloy-rs/op-alloy/issues/27
To be able to replace `UnsingedTx` and `TxEnvelope` on Optimism network with op-consensus types, we need a op-specific tx builder.
Add `OpTransactionBuilder` which is a wrapper around `TransactionBuilder`. It intentionally does not have any direct methods allowing to set EIP-4844 fields, however they can still be set through `AsMut` or during deserialization.
When building typed transaction, eip-4844 transactions are getting converted to eip-1559
=> feat: `OpTransactionRequest`

.github/workflows/ci.yml, Justfile
Fixes the feature powerset in ci to exclude `op-alloy` due to combinatorial overflow.
=> fix: ci powerset

.github/workflows/ci.yml
Removes the publishing of basic docs to gh-pages. There's now a nice mdbook that's published by the books.yml workflow.
=> fix(ci): Remove Docs gh-page publish

crates/rpc-jsonrpsee/Cargo.toml, crates/rpc-jsonrpsee/src/lib.rs, crates/rpc-jsonrpsee/src/traits.rs
related issues  https://github.com/paradigmxyz/reth/issues/12275
=> feat: add jsonrpsee trait for SuperchainSignal

book/src/SUMMARY.md, book/src/examples/README.md, book/src/examples/load-a-rollup-config.md
Loading a rollup config example.
=> chore(book): Load Rollup Config Example

Cargo.toml, crates/consensus/src/lib.rs, crates/consensus/src/transaction/deposit.rs, crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/mod.rs, crates/consensus/src/transaction/typed.rs, crates/protocol/src/batch/raw.rs, crates/protocol/src/batch/transactions.rs, crates/protocol/src/batch/tx_data/eip1559.rs, crates/protocol/src/batch/tx_data/eip2930.rs, crates/protocol/src/batch/tx_data/legacy.rs, crates/protocol/src/batch/tx_data/wrapper.rs, crates/protocol/src/lib.rs, crates/protocol/src/utils.rs, crates/rpc-types/Cargo.toml, crates/rpc-types/src/transaction.rs, crates/rpc-types/src/transaction/request.rs, scripts/check_no_std.sh
Bumps alloy, alloy-core and alloy-eip7702.
Code changes: 
- https://github.com/alloy-rs/alloy/pull/1496 changed transaction encoding API, encoding functions are now prefixed with `rlp`,`eip2718` or `network`. I've updated `TxDeposit` to have methods following this pattern
- https://github.com/alloy-rs/core/pull/776 updated signature type to avoid using `Parity` generic and instead just keep a boolean for parity byte. The motivation is to have more correctness in encoding and data structure. Before that it was possible to construct `Signed<TxLegacy>` where transaction chain_id is `Some`, but the parity would not follow EIP-155.
This required a few changes to `SpanBatchTransactions` type:
- `encode_y_parity_bits` and `encode_tx_sigs_rs` are merged into single `encode_tx_sigs` which firstly …
=> [wip] feat: bump alloy

crates/protocol/src/fee.rs, crates/rpc-types-engine/Cargo.toml, crates/rpc-types-engine/src/attributes.rs, crates/rpc-types-engine/src/error.rs, crates/rpc-types-engine/src/lib.rs
~~blocked by #205~~
ported from reth
=> feat: add holocene extradata fn

book/src/starting/installation.md
=> fix(book): Links Imports

book/src/building/rpc_types.md
Adds small docs for `op-alloy-rpc-types`
=> chore(book): RPC Types

Cargo.toml, crates/rpc-types/src/transaction.rs
=> feat: bump alloy

crates/consensus/src/transaction/envelope.rs
Broken decoding for eip7702
Adds conversion from u8 to `OpTxType::Eip7702`
=> fix(consensus): add conversion for `OpTxType::Eip7702`

crates/rpc-types/src/transaction.rs
ref https://github.com/paradigmxyz/reth/pull/12474
We need a separate `deposit_nonce` to account for deposit transaction responses which have it while it's not present in inner envelope.
Adds `nonce` field to `OptionalFields` helper. It would get deserialized only if envelope did not consume it and serialized only if present and inner envelope is a deposit
=> feat: add nonce to RPC transaction

Cargo.toml, crates/consensus/src/hardforks/ecotone.rs, crates/consensus/src/hardforks/fjord.rs, crates/consensus/src/transaction/deposit.rs, crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/typed.rs, crates/protocol/src/block_info.rs, crates/protocol/src/deposits.rs, crates/rpc-types/src/transaction/request.rs
ref https://t.me/paradigm_reth/36099
Makes envelope more consistend by making all variants hold a hash
=> feat: wrap `TxDeposit` into `Sealed` in `OpTxEnvelope`

crates/protocol/src/batch/bits.rs, crates/protocol/src/batch/core.rs, crates/protocol/src/batch/errors.rs, crates/protocol/src/batch/mod.rs, crates/protocol/src/batch/payload.rs, crates/protocol/src/batch/prefix.rs, crates/protocol/src/batch/raw.rs, crates/protocol/src/batch/transactions.rs, crates/protocol/src/lib.rs
Implements encoding for batch types.
Steps in the direction to batch submission.
=> feat(protocol): Batch Encoding

crates/protocol/src/errors.rs, crates/protocol/src/lib.rs, crates/protocol/src/utils.rs
Removes public visibility from modules so crate docs don't show all the `pub use mod::*` types as re-exported.
Also moves error types from `utils` into a new `errors` module.
=> chore(protocol): Re-organizes Modules and Errors

Cargo.toml, crates/consensus/src/receipt/envelope.rs, crates/protocol/Cargo.toml, crates/protocol/examples/batch_to_frames.rs, crates/protocol/src/channel.rs, crates/protocol/src/lib.rs, crates/protocol/src/utils.rs
Adds batch compression to the `ChannelOut`.
=> feat(protocol): Brotli Compression behind `std`

crates/protocol/src/batch/core.rs, crates/protocol/src/batch/raw.rs, crates/protocol/src/batch/span.rs
Removes the `TryFrom` span batch for `RawSpanBatch`, inlining the coercion into a `to_raw_span_batch` method.
Closes #266.
=> chore(protocol): Remove TryFrom

crates/consensus/Cargo.toml, crates/consensus/src/eip1559.rs, crates/genesis/Cargo.toml, crates/genesis/src/system.rs, crates/protocol/src/block_info.rs, crates/protocol/src/deposits.rs
Removes error impls using `thiserror` instead.
=> chore: Remove Error Impls

crates/genesis/src/lib.rs
Removes re-exports from `op-alloy-genesis`.
=> chore(genesis): Remove Re-exports

book/src/examples/batch-to-frames.md, book/src/examples/frames-to-batch.md, book/src/links.md, crates/protocol/examples/frames_to_batch.rs
Cleans up `op-alloy-protocol` examples using the exported `decompress_brotli` method.
=> chore(protocol): Cleanup Examples

crates/consensus/src/hardforks/ecotone.rs, crates/consensus/src/hardforks/fjord.rs, crates/consensus/src/hardforks/mod.rs
Simplifies signature definitions.
Closes #59.
=> chore(consensus): Signature Definitions

.github/workflows/ci.yml, .gitmodules, Cargo.toml, Justfile, crates/registry/Cargo.toml, crates/registry/Justfile, crates/registry/README.md, crates/registry/etc/bind.sh, crates/registry/etc/chainList.json, crates/registry/etc/configs.json, crates/registry/src/chain_list.rs, crates/registry/src/lib.rs, crates/registry/src/superchain.rs
Migrates `superchain-registry` crate into `op-alloy` so hardcoded configs and periphery methods in `op-alloy-genesis` can be removed.
Since `op-alloy-registry` is `no_std`, we can use the rollup configs parsed from the `ethereum-optimism/superchain-registry` directly
instead of defining custom hardcoded registries.
=> feat: Introduce op-alloy-registry

crates/genesis/src/chain.rs
Fixes base fee param loading in the `ChainConfig` -> `RollupConfig` conversion to actually pull in the `OpBaseFeeParams` defined in the `optimism` field of the `ChainConfig`.
=> fix(genesis): Base Fee Params

crates/consensus/src/transaction/tx_type.rs
doesn't hurt, need this because default enforced in reth for testing
=> chore: add default for txtype

crates/protocol/src/block.rs, crates/protocol/src/info/bedrock.rs, crates/protocol/src/info/ecotone.rs, crates/protocol/src/info/errors.rs, crates/protocol/src/info/mod.rs, crates/protocol/src/info/variant.rs, crates/protocol/src/lib.rs
Refactors the `block_info.rs` module into a new `info/` module that makes the `L1BlockInfoTx` more extensible.
Closes #302
=> chore(protocol): Refactor Block Info Txs

crates/consensus/src/hardforks/ecotone.rs, crates/consensus/src/hardforks/fjord.rs, crates/consensus/src/transaction/deposit.rs, crates/consensus/src/transaction/envelope.rs, crates/protocol/src/deposits.rs
Moves custom EIP-2718 encoding and decoding methods on `TxDeposit` into trait impls for the alloy eip traits.
=> chore(consensus): EIP-2718 Encoding Trait Impls

crates/op-alloy/src/lib.rs, scripts/check_no_std.sh
Adds missing crates to the `no_std` checks that support `no_std`.
=> chore(ci): Add missing no_std crates

crates/op-alloy/Cargo.toml, crates/op-alloy/src/lib.rs
Adds the missing `op-alloy-registry` to the `op-alloy` aggregator crate under the `registry` feature flag.
=> fix(op-alloy): Add Missing Registry Crate

crates/consensus/src/eip1559.rs, crates/genesis/src/system.rs, crates/protocol/src/channel.rs, crates/protocol/src/deposits.rs, crates/protocol/src/frame.rs, crates/protocol/src/info/errors.rs
When using [`thiserror::Error`][error] with `#[error(..)]` attributes, a `Display` impl [is generated for the error](https://github.com/dtolnay/thiserror?tab=readme-ov-file#details).
This PR removes all hand-rolled Display impls for errors, using `thiserror::Error` with `#[error]` attributes on variants.
[error]: https://docs.rs/thiserror/latest/thiserror/derive.Error.html
=> chore(workspace): Remove Hand-rolled Display Error Impls

crates/genesis/src/chain.rs, crates/genesis/src/rollup.rs, crates/registry/src/superchain.rs
Dogfoods the hardcoded test rollup config and uses the new `From<&RollupConfig> for HardForkConfiguration`.
=> chore(registry): Dogfood Test Rollup Config

crates/consensus/Cargo.toml, crates/genesis/Cargo.toml, crates/protocol/Cargo.toml, crates/rpc-types-engine/Cargo.toml
Enables 
Running tests individually locally fails.
Enable `arbitrary` feature for `alloy-primtives` in dev-deps.
=> Enable alloy-primitives/arbitrary in dev-deps

crates/consensus/src/transaction/envelope.rs
Adds a helper method to the `OpTxEnvelope` to return the inner transaction hash.
=> feat(consensus): tx envelope tx hash

crates/consensus/src/receipt/receipts.rs
Reuses methods from alloy receipt for deposit receipt and makes them pub for reuse in reth
=> chore: reuse methods for receipt rlp

crates/consensus/src/eip1559.rs, crates/consensus/src/lib.rs, crates/rpc-types-engine/src/attributes.rs
add reth function with was duplicated code
https://github.com/paradigmxyz/reth/blob/c816a3b758a39640388cc179abafd924ff9103b9/crates/optimism/chainspec/src/lib.rs#L268-L279
we already have the `decode_eip_1559_params` fn but were missing the decode from extradata slice.
this renames the previous `decode_holocene_extra_data` function to encode_ because this actually encodes
=> feat: upstream decode extradata fn

crates/consensus/src/lib.rs, crates/consensus/src/transaction/mod.rs, crates/consensus/src/transaction/pooled.rs
We need a type that represents a pooled transaction, this cannot include deposit transactions
Implemented `OpPooledTransaction`, which is like `OpTxEnvelope` but without the deposit variant.
=> feat: add OpPooledTransaction

crates/rpc-jsonrpsee/src/traits.rs
op batcher prints error
`ERROR[12-17|18:17:23.568] Result of SetMaxDASize was false, retrying.`
command for op-bathcer
```shell
op-batcher \
--l2-eth-rpc=http://localhost:8545 \
--rollup-rpc=http://localhost:9545 \
--poll-interval=1s \
--sub-safety-margin=6 \
--num-confirmations=1 \
--safe-abort-nonce-too-low-count=3 \
--resubmission-timeout=30s \
--rpc.addr=0.0.0.0 \
--rpc.port=8548 \
--rpc.enable-admin \
--max-channel-duration=25 \
--l1-eth-rpc=$L1_RPC_URL \
--private-key=$GS_BATCHER_PRIVATE_KEY
```
golang implementation of optimism's op-geth [returns bool](https://github.com/ethereum-optimism/op-geth/blob/optimism/eth/api_miner.go#L62) type for `miner_setMaxDASize` call. Therefore, expected response might be like following:
```json
{
"jsonrpc": "2.0",
"id": 0,
"result": true
}
```
On …
=> [Bug] miner_setMaxDASize should return bool type

.github/workflows/ci.yml, crates/rpc-jsonrpsee/Cargo.toml, crates/rpc-jsonrpsee/src/lib.rs, crates/rpc-jsonrpsee/src/traits.rs
Closes https://github.com/alloy-rs/op-alloy/issues/355
Adds `no_std` support `op-alloy-rpc-jsonrpsee`, and removes exclusion from CI wasm check
=> chore(rpc): `no_std` support `op-alloy-rpc-jsonrpsee`

crates/protocol/Cargo.toml, crates/protocol/src/lib.rs, crates/protocol/src/messages/events.rs, crates/protocol/src/messages/mod.rs, crates/protocol/src/messages/safety.rs
Adds interop message types to `op-alloy-protocol` following the [ExecutingMessage spec](https://github.com/ethereum-optimism/specs/blob/main/specs/interop/predeploys.md#executingmessage-event)
and the associated [op-geth code](https://github.com/ethereum-optimism/op-geth/blob/optimism/core/types/interoptypes/interop.go).
=> feat(protocol): Interop Types

crates/protocol/Cargo.toml, crates/protocol/src/lib.rs, crates/protocol/src/messages/events.rs, crates/protocol/src/messages/mod.rs
Closes https://github.com/alloy-rs/op-alloy/issues/360
Defines `ExecutingMessage` wrapper for `ExecutingMessageAbi`.
=> feat(interop): Define `ExecutingMessage` wrapper

CHANGELOG.md, Cargo.toml
=> release: 0.9.1

Cargo.toml, crates/rpc-types-engine/Cargo.toml, crates/rpc-types-engine/src/lib.rs
Touches up #367 to use `maili-rpc-types-engine` instead of `maili`.
=> fix: Use maili-rpc-types-engine

crates/genesis/src/chain.rs, crates/genesis/src/rollup.rs
Adds a new optional `interop_time` field to `RollupConfig` + `HardForkConfiguration`.
=> chore(genesis): Add `interop_time` to `RollupConfig` + `HardForkConfiguration`

crates/op-alloy/Cargo.toml, crates/op-alloy/src/lib.rs
Adds `op-alloy-provider` back to the `op-alloy` crate.
=> fix: op-alloy-provider

Cargo.toml
Bumps the version of `maili` crates in the workspace to the latest release.
=> chore: Bump `maili-*` to `0.1.6`

crates/consensus/src/transaction/envelope.rs, crates/rpc-types/src/transaction.rs
This is a useful helper method for when you have a concrete `OpTxEnvelope` and want to know whether or not it's a deposit transaction.
Adds `fn is_deposit`
=> feat(consensus): add is_deposit to OpTxEnvelope

crates/consensus/Cargo.toml
Until reth completely moves off of `op-alloy-consensus`, and onto `maili-consensus`, we'll want to enable this transitive dependency feature from the `op-alloy-consensus` dep.
Add `serde-bincode-compat` feature to `op-alloy-consensus` and propagate to `maili-consensus`
=> chore: add serde-bincode-compat for re-export features

.github/workflows/ci.yml, Cargo.toml, README.md, book/src/links.md, book/src/starting.md, crates/consensus/Cargo.toml, crates/consensus/src/hardforks/ecotone.rs, crates/consensus/src/hardforks/fjord.rs, crates/consensus/src/lib.rs, crates/consensus/src/source.rs, crates/consensus/src/transaction/deposit.rs, crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/mod.rs, crates/consensus/src/transaction/tx_type.rs, crates/consensus/src/transaction/typed.rs, crates/op-alloy/Cargo.toml, crates/op-alloy/README.md, crates/op-alloy/src/lib.rs, crates/provider/Cargo.toml, crates/provider/src/ext/engine.rs, crates/rpc-jsonrpsee/Cargo.toml, crates/rpc-jsonrpsee/README.md, crates/rpc-jsonrpsee/src/lib.rs, crates/rpc-jsonrpsee/src/traits.rs, crates/rpc-types-engine/Cargo.toml, crates/rpc-types-engine/src/attributes.rs, crates/rpc-types-engine/src/lib.rs, crates/rpc-types/Cargo.toml, crates/rpc-types/src/transaction.rs, crates/rpc-types/src/transaction/request.rs
Closes https://github.com/alloy-rs/op-alloy/issues/398
this reverts a bunch of stuff and removes all maili dependencies.
this is definitely incomplete but is the first step towards restoring op-alloy as a maili independent repo.
the dep graph looks now as follows:
alloy -> op-alloy -> maili
maili can have all types limited to protocol impls (although debatable if this is actually beneficial, imo this just slows down development atm).
next steps are invert deps on maili side and clean things up there.
this repo would benefit from the flz stuff, so I suggest we move this crate in here and only keep the brotli stuff in maili
=> chore: revert maili deps

Cargo.toml, crates/flz/Cargo.toml, crates/flz/README.md, crates/flz/src/lib.rs
adds standalone flz repo
this could eventually be converted into a standalone crate, if revm is willing to import that and remove code dup
=> feat: add flz

.config/zepter.yaml, .github/workflows/lint.yml, crates/network/Cargo.toml, crates/op-alloy/Cargo.toml, crates/provider/Cargo.toml, crates/rpc-types-engine/Cargo.toml, crates/rpc-types/Cargo.toml
Closes #332.
Add feature propagation checks to CI.
=> feat(ci): Add feature propagation checks

crates/provider/src/ext/engine.rs
=> chore: rm execution requests from v4 payload fn

crates/consensus/src/receipt/envelope.rs, crates/consensus/src/transaction/envelope.rs, crates/rpc-types/src/receipt.rs
these are sleeping timebombs because these require the user to add an unreachable arm
=> chore: rm bad non_exhaustive

crates/rpc-types-engine/src/envelope.rs, crates/rpc-types-engine/src/lib.rs, crates/rpc-types-engine/src/payload/mod.rs
Closes https://github.com/alloy-rs/op-alloy/issues/417
- Defines `OpExecutionData` which wraps `OpExecutionPayload` and `OpExecutionPayloadSidecar`
- Debugs `OpExecutionPayload`
- Removes `OpExecutionPayloadV4`, since the l2 withdrawals root goes in sidecar, it doesn't add an extra field to the header
=> feat(isthmus): define `OpExecutionData`

crates/rpc-types-engine/src/payload/v4.rs
Ref https://github.com/alloy-rs/op-alloy/issues/421
=> feat(l2-withdrawals): Impl conversion to block for `OpExecutionPayloadV4`

crates/consensus/src/transaction/typed.rs
this returns an option because deposits are not signed.
=> feat: add fn for signature hash

crates/consensus/src/lib.rs, crates/consensus/src/receipt/mod.rs, crates/consensus/src/receipt/receipts.rs, crates/consensus/src/transaction/typed.rs
closes #424
ensures this type can be used when doing bincode style serde where flatten or skipped fields are not supported
this is so annoying ...
=> feat: add bincode compat support for depositreceipts

crates/rpc-types-engine/src/payload/error.rs, crates/rpc-types-engine/src/payload/mod.rs
Pre-req for l2-withdrawals is that the payload validation diverges from l1 payload validation. Adds stateless payload checks to `OpExecutionPayload::try_into_block`
=> feat(l2-withdrawals): Add `OpPayloadError` variants for blob transactions and l1 withdrawals

crates/rpc-types-engine/src/sidecar.rs
Adds methods for accessing Prague fields to `OpExecutionPayloadSidecar`
=> feat(l2-withdrawals): Add methods for prague payload fields to `OpExecutionPayloadSidecar`

crates/rpc-types/src/genesis.rs
Closes https://github.com/alloy-rs/op-alloy/issues/446 
For https://github.com/paradigmxyz/reth/pull/14582
=> Add interop time to genesis

crates/consensus/src/receipt/receipts.rs
this can be flaky if the arbitrary status is Postate which does not exist for OP
=> test: fix flaky bincode compat rountrip test

crates/rpc-types-engine/src/envelope.rs, crates/rpc-types-engine/src/payload/mod.rs
- Adds missing variant `OpExecutionPayload::V1`, needed to support conversion from `ExecutionPayloadInputV2`
- Fixes buggy `as_mut` methods for `OpExecutionPayload`
- Adds conversion from `newPayload` args to `OpExecutionData`
=> feat(l2-withdrawals-root): Add conversions for `OpExecutionData`

crates/rpc-types-engine/src/envelope.rs, crates/rpc-types-engine/src/payload/v4.rs
No need for method `OpExecutionPayloadV4::withdrawals` and the types it imports, since the inner payload is in a publicly accessible field anyways. This list of withdrawals should always be empty.
=> Remove redundant method for v4 payload

crates/consensus/src/transaction/typed.rs
this is quite useful and we don't expect this to be used for deposits
=> feat: add signabletx impl for typedtx

crates/consensus/src/transaction/envelope.rs
Implements `AsRef<OpTxEnvelope>` over itself so a generic tx type that implements `AsRef<OpTxEnvelope>` can be specified.
Basically, we need a way to convert the [`op_alloy_rpc_types::Transaction`](https://docs.rs/op-alloy-rpc-types/latest/op_alloy_rpc_types/struct.Transaction.html#impl-AsRef%3COpTxEnvelope%3E-for-Transaction)
type into an `OpTxEnvelope`. Since it implements `AsRef<OpTxEnvelope>`, we can just implement `AsRef` over `OpTxEnvelope` itself so we can restrict a generic
`T: AsRef<OpTxEnvelope>` and use either `OpTxEnvelope` or `op_alloy_rpc_types::Transaction`.
See: https://github.com/op-rs/kona/pull/1176
=> chore(consensus): AsRef<OpTxEnvelope>

Cargo.toml, crates/consensus/Cargo.toml, crates/consensus/src/alloy_compat.rs, crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/pooled.rs, crates/consensus/src/transaction/typed.rs, crates/rpc-types/Cargo.toml, crates/rpc-types/src/transaction.rs
Bump alloy to `0.12`
Closes #316 
- Bump alloy deps (using patch until 0.12 release)
- Bump alloy-core
- Impl RlpEcdsaEncodableTx for OpTypedTransaction
=> chore(deps): alloy 0.12

crates/consensus/src/source.rs, crates/consensus/src/transaction/deposit.rs
Removes the deposit context source, which is no longer necessary as a part of the interop upgrade.
=> chore: Remove deposit context source

crates/rpc-types-engine/src/envelope.rs
Fixes the payload hash for the V3 + V4 topic.
spec: https://specs.optimism.io/protocol/rollup-node-p2p.html#block-signatures
=> fix(rpc-types-engine): Fix `PayloadHash` for V3 + V4 topic

crates/consensus/src/transaction/envelope.rs
hash fn is a bit of a mess rn, we have hash, hash_ref and tx_hash.
this follows the convention that hash should return a ref.
before next breaking release we should make this more consistent
=> feat: add hash ref function

crates/consensus/src/transaction/envelope.rs, crates/rpc-types-engine/src/envelope.rs, crates/rpc-types-engine/src/lib.rs
Implements ssz payload encoding for gossiping `OpNetworkPayloadEnvelope`s via consensus p2p.
=> feat(rpc-types-engine): SSZ Payload Encoding

book/src/building/README.md, book/src/building/engine.md, book/src/building/rpc_types.md
Hi! I found a bunch of outdated doc links in the `building/` section of the book — most of them were either missing subpaths or pointing to outdated versions.
...
=> docs: fix broken links in `building` section

crates/consensus/src/source.rs
Adds the interop block replacement deposit source, as specified in [interop derivation](https://specs.optimism.io/interop/derivation.html#optimistic-block-source-hash).
=> feat(consensus): Add interop block replacement deposit source

book/src/SUMMARY.md, book/src/intro.md
I recommend removing the broken [Examples] section from both SUMMARY.md and intro.md, as the path ./examples/README.md no longer exists in the repository.
If there is a different location or an updated file that should replace this link, feel free to suggest it, and I will update the references accordingly.
=> Fix: Remove broken Examples links

book/src/links.md
Updates the documentation link for OpTxEnvelope to point to the correct location under the transaction namespace.
Changes:
- Updates link from `/enum.OpTxEnvelope.html` to /`transaction/enum.OpTxEnvelope.html`
=> Update OpTxEnvelope documentation link path

crates/provider/src/ext/engine.rs, deny.toml
Fixes the engine api to use the `OpExecutionPayloadV4` type with the withdrawals root. Without this, V4 engine api methods post-isthmus will error since the `withdrawalsRoot` field *must* not be nil.
=> fix(engine): Use OpExecutionPayloadV4

crates/provider/src/ext/engine.rs
Adds support for the [`engine_signalSuperchainV1`](https://specs.optimism.io/protocol/exec-engine.html#engine_signalsuperchainv1)
to the `OpEngineApi` trait.
Uses the `SuperchainSignal` and `ProtocolVersion` types defined in `op_alloy_rpc_types_engine`.
=> feat(engine): Superchain Signal

crates/rpc-types-engine/src/superchain.rs
Implement error on the `ProtocolVersionError` type.
=> fix(rpc-types-engine): Error Implementation

crates/consensus/src/transaction/deposit.rs, crates/consensus/src/transaction/envelope.rs
=> feat: made TxDeposit's mint field non-optional

crates/consensus/src/transaction/envelope.rs, crates/consensus/src/transaction/pooled.rs
Ref https://github.com/paradigmxyz/reth/issues/16411
`Extended` type is moved from Reth to Alloy.
So it also needs to move `TryFrom`, `From` trait conversions to op-alloy
=> feat: add Extended conversions for OpPooledTransaction, OpTxEnvelope

crates/rpc-types/src/error.rs
Changes repr of `InvalidInboxEntry` to `i32` for better conversion to `jsonrpsee::ErrorObjectOwned` error code
=> Change `InvalidInboxEntry` repr `i64`->`i32` for `jsonrpsee` error compat

book/src/intro.md
link doesn't work here https://alloy-rs.github.io/op-alloy/ 
just fixed.
=> fix link to starting.md

crates/rpc-types/Cargo.toml, crates/rpc-types/src/error.rs, crates/rpc-types/src/lib.rs
Renames `InvalidInboxEntry` to `SuperchainDAError`.
Some of these error variants occur also on updating superchain state. The name `InvalidInboxEntry` is to specialised for `supervisor_checkAccessList`.
Adds feature `jsonrpsee` to `op-alloy-rpc-types` and feature gated conversion to `jsonrpsee::ErrorObjectOwned`.
=> feat(interop): Rename `InvalidInboxEntry`->`SuperchainDAError`

.config/zepter.yaml, book/src/SUMMARY.md
In .config/zepter.yaml:
Changed expose → exposes to fix verb form agreement.
Changed A it outside → A is outside to fix grammar and remove incorrect structure.
In book/src/SUMMARY.md:
Removed the line linking to ./examples/load-a-rollup-config.md because the file doesn't exist or is no longer used.
These changes improve documentation clarity and prevent confusion or broken links in the rendered docs.
=> docs: grammar fixes and a cleanup of a broken documentation link

crates/consensus/src/receipt/receipts.rs, crates/consensus/src/transaction/envelope.rs
smol helper for converting rpc op tx info via envelope type
=> chore: add smol conversion helper

book/src/links.md
non working link is on this page https://alloy-rs.github.io/op-alloy/building/consensus.html
=> [docs]: fix link to Enum OpTxType

crates/rpc-types-engine/src/envelope.rs, crates/rpc-types-engine/src/lib.rs
A thin wrapper around `OpExecutionPayload` that includes the parent beacon block root that provides a rust-equivalent to [`ExecutionPayloadEnvelope`](https://github.com/ethereum-optimism/optimism/blob/7c812674f9e2068949a152f44fde13fcb93b2c45/op-service/eth/types.go#L233).
This is required for a serialized rpc type in the op admin api to post unsafe payloads.
=> feat(rpc-types-engine): OpExecutionPayload Wrapper

crates/consensus/src/interop.rs, crates/rpc-types/Cargo.toml, crates/rpc-types/src/error.rs, crates/rpc-types/src/lib.rs
Updates `SafetyLevel` variant names to match Go impl
Ref https://github.com/ethereum-optimism/specs/issues/717
=> chore(consensus): Rename `SafetyLevel` variants `Unsafe`->`LocalUnsafe` and `Safe`->`CrossSafe`

crates/consensus/src/lib.rs, crates/consensus/src/transaction/envelope.rs
Follow-up on #548 
`OpTransaction` trait can tell if its deposit, but that is not very useful if I also need to extract it.
Add `as_deposit` function into the trait for the extraction of `TxDeposit`.
=> feat(consensus): Add `as_deposit` into `OpTransaction` trait

crates/rpc-types-engine/src/payload/mod.rs
```markdown
A small typo was corrected in a comment within the `OpExecutionPayload` implementation. This improves the clarity of the documentation.
- **File:** `crates/rpc-types-engine/src/payload/mod.rs`
- **Change:** "preformed" -> "performed"
```
=> docs: fix typo in payload comment

book/src/building/engine.md
The previous link for [engine] in book/src/building/engine.md pointed to the documentation page for OpAttributesWithParent in the op-alloy-rpc-types-engine crate. However, this struct no longer exists in the latest published documentation, resulting in a 404 error.
To avoid broken links and ensure users are directed to relevant and up-to-date documentation, the link was updated to the root documentation page for the op-alloy-rpc-types-engine crate on docs.rs. This approach ensures that users can always access the latest available types and modules, even if specific items are renamed, moved, or removed in future versions. If a more specific and stable documentation page becomes available in the future, the link can be updated accordingly.
=> Update broken OpAttributesWithParent docs.rs link to crate root in engine.md

crates/rpc-types-engine/src/payload/mod.rs, crates/rpc-types-engine/src/payload/v4.rs
Adds custom transaction mapping functionality to OpExecutionPayload types, following the same pattern as https://github.com/alloy-rs/alloy/pull/2495.
- Add `try_into_block_with` method to `OpExecutionPayloadV4` that accepts a custom transaction mapper
- Add `try_into_block_with` method to `OpExecutionPayload` enum for all payload versions
- Add `try_into_block_with_sidecar_with` method to `OpExecutionPayload` for sidecar conversions with custom mapping
- Update existing `try_into_block` methods to use the new `_with` variants internally
This enables more flexible transaction decoding when converting execution payloads to blocks, allowing callers to provide their own transaction decoding logic while maintaining the same validation checks.
=> feat: add try_into_block_with methods to OpExecutionPayload
